/// 
Class HealthToolKit.BP.FHIRRouter Extends Ens.BusinessProcessBPL
{

/// BPL Definition
XData BPL [ XMLNamespace = "http://www.intersystems.com/bpl" ]
{
<process language='objectscript' request='Ens.Request' response='Ens.Response' height='2000' width='2000' >
<sequence xend='200' yend='600' >
<if name='Transform ?' condition='request.Request.RequestPath [ "hl7"' xpos='200' ypos='250' xend='200' yend='500' >
<true>
<call name='To Transform' target='FHIR_SDA' async='0' xpos='470' ypos='400' >
<request type='Ens.Request' >
<assign property="callrequest" value="request" action="set" />
</request>
<response type='Ens.Response' >
<assign property="response" value="callresponse" action="set" />
</response>
</call>
</true>
<false>
<call name='To Repo' target='FHIR_Local_Operation' async='0' xpos='200' ypos='400' >
<request type='Ens.Request' >
<assign property="callrequest" value="request" action="set" />
</request>
<response type='Ens.Response' >
<assign property="response" value="callresponse" action="set" />
</response>
</call>
</false>
</if>
</sequence>
</process>
}


}
